version: "3"
services:
  myservice:
    runtime: nvidia
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "60000:8888" # port for JupyterLab (or JupyterNotebook)
      - "2222:22"
    volumes:
      - .:/simple-train-winedb
    networks:
      - mynetwork
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    tty: true
    stdin_open: true
    command: /usr/sbin/sshd -D
networks:
  mynetwork:
